//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Windows.Media.Imaging;
namespace Lab01
{
    using System;
    using System.Collections.Generic;
    
    public partial class NasaBase
    {
        public string Date { get; set; }
        public int CloudScore { get; set; }
        public int Longitude { get; set; }
        public int Latitude { get; set; }
        public BitmapImage Image { get; set; }
        public string ID { get; set; }
    }
}
